# Site settings
title: Andrew (Reynolds) Manion
description: My personal site.
baseurl: "/reynolds" # Add this line

# Build settings
theme: jekyll-theme-slate
url: "https://ar16man.github.io" # Optional, but good practice
